name: Docker Image CI

on:
  push:
    branches: [ "Main" ]
  pull_request:
    branches: [ "Main" ]

jobs:

  build:
    if: "contains(github.event.head_commit.message, '#build')"
    name: Build API Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file ./build/Docker/Dockerfile --tag amzn_api:$SHORT_SHA
